import Head from "next/head";
import catego from "../categories.json";
import MenuIterativo from "../components/menuIterativo";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Diversos Componentes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MenuIterativo categories={catego} />
    </div>
  );
}
